### ISSUE TITLE
draft-tjjk-cared

### ISSUE THREAD

**Issue by wkumari** [wkumari/Temp-DNSOP_Doc_Tracker#18]
## Link: 
[[draft-tjjk-cared - "Client Authentication Recommendations for Encrypted DNS"](https://datatracker.ietf.org/doc/draft-tjjk-cared/)](https://datatracker.ietf.org/doc/draft-tjjk-cared/)

## Authors:

  * Tommy Jensen
  * Jessica Krynitsky
  * Jeffrey Damick
  * Matt Engskow

**Comment by wkumari** [comment]
It has been suggested that UTA might be a better fit than DNSOP.

Suzanne will reach out to UTA chairs to see if the document better fits there.

If it goes to UTA:
 * It should be presented every now and then at DNSOP meetings.
 * The WGLC should be CCed to DNSOP.
 * The DNSDIR should be included in discussions.

**Comment by moonshiner** [comment]
Okay the decision appears to be UTA is the place for this.
