### ISSUE TITLE
draft-ietf-dnsop-qdcount-is-one

### ISSUE THREAD

**Issue by wkumari** [wkumari/Temp-DNSOP_Doc_Tracker#5]
## Link: 
https://datatracker.ietf.org/doc/draft-ietf-dnsop-qdcount-is-one/

## Authors:
* Ray Bellis
* Joe Abley

**Comment by moonshiner** [comment]
Shepherd w/up in process

**Comment by wkumari** [comment]
[[RFC9619 - "In the DNS, QDCOUNT Is (Usually) One"](https://datatracker.ietf.org/doc/rfc9619/)](https://datatracker.ietf.org/doc/rfc9619/)
